### ISSUE TITLE
api key expired ?

### ISSUE THREAD

**Issue by aerphanas** [Xnuvers007/Waifu2x#1]
### Subject of the issue
Api key does't work, key expired ?
- https://github.com/Xnuvers007/Waifu2x/blob/9857fa7ef07a0cb304c11fea8915e052c264c9e4/waifu2x.py#L97
- https://github.com/Xnuvers007/Waifu2x/blob/9857fa7ef07a0cb304c11fea8915e052c264c9e4/waifu2x.py#L52

###  environment
```sh
curl --version
curl 7.87.0 (x86_64-pc-linux-gnu) libcurl/7.87.0 OpenSSL/3.0.8 zlib/1.2.13 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.4 libpsl/0.21.2 (+libidn2/2.3.4) libssh2/1.10.0 nghttp2/1.51.0
```

### Steps to reproduce

sending https request with curl
```sh
curl https://api.deepai.org/api/waifu2x \
       -F 'image=`'$(url)'` \
       -H 'api-key:6bb16995-6df5-4b3d-a4b7-f0973f56ea82' \
```

### Expected behaviour

get json response : 
```sh
{
    "id": "3fd6d00d-371c-4152-aa12-4e28af3904xx",
    "output_url": "https://api.deepai.org/job-view-file/x/x/x.png"
}
```

### Actual behaviour

```sh
{"err": "error processing given inputs from request"}
```

**Comment by Xnuvers007** [comment]
> ### Subject of the issue
> Api key does't work, key expired ?
> 
> * https://github.com/Xnuvers007/Waifu2x/blob/9857fa7ef07a0cb304c11fea8915e052c264c9e4/waifu2x.py#L97
> * https://github.com/Xnuvers007/Waifu2x/blob/9857fa7ef07a0cb304c11fea8915e052c264c9e4/waifu2x.py#L52
> 
> ### environment
> ```shell
> curl --version
> curl 7.87.0 (x86_64-pc-linux-gnu) libcurl/7.87.0 OpenSSL/3.0.8 zlib/1.2.13 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.4 libpsl/0.21.2 (+libidn2/2.3.4) libssh2/1.10.0 nghttp2/1.51.0
> ```
> 
> ### Steps to reproduce
> sending https request with curl
> 
> ```shell
> curl https://api.deepai.org/api/waifu2x \
>        -F 'image=`'$(url)'` \
>        -H 'api-key:6bb16995-6df5-4b3d-a4b7-f0973f56ea82' \
> ```
> 
> ### Expected behaviour
> get json response :
> 
> ```shell
> {
>     "id": "3fd6d00d-371c-4152-aa12-4e28af3904xx",
>     "output_url": "https://api.deepai.org/job-view-file/x/x/x.png"
> }
> ```
> 
> ### Actual behaviour
> ```shell
> {"err": "error processing given inputs from request"}
> ```

btw, you can use your own apikey in [here and login/sign-up](https://deepai.org/machine-learning-model/waifu2x)
or you can use this apikey maybe **quickstart-QUdJIGlzIGNvbWluZy4uLi4K**
